#!/bin/bash

## sshd back
cp /etc/ssh/sshd_config /etc/ssh/sshd_back > /dev/null 2>&1

## Acceso Rapido
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1

## Version
rm -rf $HOME/versao*; wget https://github.com/GeralNetSSH?tab/Script/SSHPLUS/master/versao > /dev/null 2>&1

## Reinstalar
echo "apt-get update -y; apt-get upgrade -y; wget https://github.com/GeralNetSSH?tab/Script/SSHPLUS/master/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus && chmod +x /bin/sshplus > /dev/null 2>&1

## Menu
wget -O /bin/menuV1 https://github.com/GeralNetSSH?tab/Script/SSHPLUS/master/Install/menuV1 > /dev/null 2>&1
chmod +x /bin/menuV1 > /dev/null 2>&1
wget -O /bin/menuV2 https://github.com/GeralNetSSH?tab/Script/SSHPLUS/master/Install/menuV2 > /dev/null 2>&1
chmod +x /bin/menuV2 > /dev/null 2>&1
wget -O /bin/menuV3 https://github.com/GeralNetSSH?tab/Script/SSHPLUS/master/Install/menuV3 > /dev/null 2>&1
chmod +x /bin/menuV3 > /dev/null 2>&1

## Systemverify
rm -rf $HOME/systemverify* > /dev/null 2>&1

#fim